### ISSUE TITLE
VSCode: Missing package Microsoft.EntityFrameworkCore.Design when generating movies scaffolded page

### ISSUE THREAD

**Issue by clarenceb** [aspnet/Docs#10519]
VSCode instructions omit the step:

`dotnet add package Microsoft.EntityFrameworkCore.Design`

which is required to generate the scaffolded page.  

Before (error):

```
dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=2.2.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.&lt;BuildCommandLine&gt;b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:06.66
```

After (working):

```
dotnet add package Microsoft.EntityFrameworkCore.Design

dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.2.1-servicing-10028 initialized 'RazorPagesMovieContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
Added Razor Page : \Pages\Movies\Create.cshtml
Added PageModel : \Pages\Movies\Create.cshtml.cs
Added Razor Page : \Pages\Movies\Edit.cshtml
Added PageModel : \Pages\Movies\Edit.cshtml.cs
Added Razor Page : \Pages\Movies\Details.cshtml
Added PageModel : \Pages\Movies\Details.cshtml.cs
Added Razor Page : \Pages\Movies\Delete.cshtml
Added PageModel : \Pages\Movies\Delete.cshtml.cs
Added Razor Page : \Pages\Movies\Index.cshtml
Added PageModel : \Pages\Movies\Index.cshtml.cs
RunTime 00:00:11.52
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@clarenceb 	I'm going to add that in #10530 because this is the 4th report. I can't repo this with the current SDK. I don't think it's required. We've got alot of folks reporting success without it - but it won't hurt to add it.
