### ISSUE TITLE
Create a web API with ASP.NET Core MVC 500 Error

### ISSUE THREAD

**Issue by drguildo** [aspnet/Docs#10581]
# Issue description

I've been following "*Tutorial: Create a web API with ASP.NET Core MVC*" and when I get to "*Add a PutTodoItem method*" and run the PUT request in Postman I get a `500 Internal Server Error` and:

_InvalidOperationException: The instance of entity type 'TodoItem' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values._

This issue has already been reported in #10289, but it was closed even though the issue wasn't fixed.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.10
 OS Platform: Linux
 RID:         ubuntu.18.10-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.503 [/usr/share/dotnet/sdk]
  2.2.103 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
</details>

**Comment by Rick-Anderson** [comment]
@drguildo 	I'm not sure what you're doing wrong but that's a pretty good error message. The code does work.
#10289 is unrelated and he was unable to repo the error.

**Comment by drguildo** [comment]
@Rick-Anderson To be sure I was using the correct code I cloned this repository and built and ran the project from there. Exact same problem.

I tried to enable `EnableSensitiveDataLogging` using `services.AddDbContext<TodoContext>(opt => opt.UseInMemoryDatabase("TodoList").EnableSensitiveDataLogging());` but it just transparently has no effect and I still get told to enable it in the exception.

**Comment by drguildo** [comment]
I just tried checking out the code on a different machine, running a different OS (Windows 7) and I still get _exactly_ the same exception.

**Comment by Rick-Anderson** [comment]
> If using the .NET Core SDK, include dotnet --info output.

**Comment by Rick-Anderson** [comment]
Per the error message, try a different `Id`.
I'm unable to reproduce the problem and we have hundreds of thousands of customers reporting success.

**Comment by Rick-Anderson** [comment]
@drguildo 	what line throws?

**Comment by drguildo** [comment]
I did include the output of `dotnet --into output` in my original report.

The full stack trace is:

```console
System.InvalidOperationException: The instance of entity type 'TodoItem' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.set_State(EntityState value)
   at TodoApi.Controllers.TodoController.PutTodoItem(Int64 id, TodoItem todoItem) in /home/sjm/tmp/Docs/aspnetcore/tutorials/first-web-api/samples/2.2/TodoApi/Controllers/TodoController.cs:line 80
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

The line that causes the exception is:

```cs
_context.Entry(todoItem).State = EntityState.Modified;
```

If I use a different ID in either the URL or payload I get:

```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Bad Request",
    "status": 400,
    "traceId": "0HLK5A8VJ9L24:00000001"
}
```

I've found something strange: it only fails if it's the first request. It seems if I make any other request first (even one that fails), then the PUT works.

**Comment by Rick-Anderson** [comment]
You need to GET before a PUT. See #10123

**Comment by drguildo** [comment]
Ahh, that explains it. I do think it would be a good idea to explain that in the tutorial and/or code seeing as I don't seem to be the only one who got confused.
