### ISSUE TITLE
Antiforgery token validation failed

### ISSUE THREAD

**Issue by ajtowf** [aspnet/Docs#1296]
When decorating a post method on a controller with the [ValidateAntiForgeryToken] we get the following error:

2016-05-26 09:22:48.342 +02:00 [Information] Antiforgery token validation failed. "The required antiforgery cookie \".AspNetCore.Antiforgery.kn8OU3FHivU\" is not present."
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.kn8OU3FHivU" is not present.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()
2016-05-26 09:22:48.346 +02:00 [Warning] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter"'.
2016-05-26 09:22:48.354 +02:00 [Information] Executing HttpStatusCodeResult, setting HTTP status code 400

This awesome blog post shows how to make it work, [http://www.stefanhendriks.com/2016/05/11/integration-testing-your-asp-net-core-app-dealing-with-anti-request-forgery-csrf-formdata-and-cookies/](http://www.stefanhendriks.com/2016/05/11/integration-testing-your-asp-net-core-app-dealing-with-anti-request-forgery-csrf-formdata-and-cookies/) it would be nice if the docs could provide a sample as well though.

**Comment by ajtowf** [comment]
Additional info: When removing the attribute the post to the controller works.

**Comment by danroth27** [comment]
@Rick-Anderson Could this be merged with the antiforgery content you have in the works?

**Comment by Rick-Anderson** [comment]
@ajtowf  That's a pretty cool blog. Looks like it shows how to do integration testing on your POST methods so you can pick up the Anti Request Forgery - is that right?  I don't think we have the budget to create a sample for this scenario.

@danroth27 so this wouldn't fit in with my planned XSRF document.
