### ISSUE TITLE
Investigate xplat scaffolding

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2647]
- Create new proj on mac - enable MVC in the project - asp.net core package and MVC package
- go to project file add microsoft.visualstudio.web.codegenrations.tools as a .NET CLI ref
- try to scaffold from the command line off the model

**Comment by Rick-Anderson** [comment]
@prafullbhosale  when will you have CLI scaffolding?

**Comment by prafullbhosale** [comment]
CLI scaffolding is already be available. 

The CLI Tool Reference in the project
```xml
<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" version="1.0.0" />
```
enables you to run scaffolding from command line. 
In addition to the steps you mentioned above, you would also need to add 
`Microsoft.VisualStudio.Web.CodeGeneration.Design` package. 
This package needs the following property in the project 
```xml
  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>
```

You can try the below commands:
`dotnet aspnet-codegenerator -h`
`dotnet aspnet-codegenerator -p <path to csproj> controller -h`

Let me know if I misunderstood your question or if this was not what you were looking for.

**Comment by Rick-Anderson** [comment]
@prafullbhosale  I created https://github.com/Rick-Anderson/MyMvc/
When I scaffold I get the following **No parameterless constructor ** error:

C:\Webs\1\MyMvc>dotnet aspnet-codegenerator  controller -name MovieController  -m Movie -dc MvcMovieContext
Command Line: controller -name MovieController -m Movie -dc MvcMovieContext
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

Building project ...
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  MyMvc -> C:\Webs\1\MyMvc\bin\Debug\netcoreapp1.1\MyMvc.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.08
Command Line: --no-dispatch --port-number 4022 controller -name MovieController -m Movie -dc MvcMovieContext --dispatcher-version 1.0.0-rtm-10308
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory
Attempting to figure out the EntityFramework metadata for the model and DbContext: Movie
No parameterless constructor was found on 'MvcMovieContext'. Either add a parameterless constructor to 'MvcMovieContext' or add an implementation of 'IDbContextFactory<MvcMovieContext>' in the same assembly as 'MvcMovieContext'. StackTrace:
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.EntityFrameworkServices.TryCreateContextUsingAppCode(Type dbContextType, Type startupType)

No parameterless constructor defined for this object. StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()

No parameterless constructor defined for this object.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:05.72

I looked at [Using IDbContextFactory](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/miscellaneous/configuring-dbcontext.md) for an example of how to create this factory - but I need some help.

Can you help me get dotnet scaffolding working for my simple Movie model

**Comment by prafullbhosale** [comment]
The problem is that the DbContext `MvcMovieContext` is not registered in the `Startup` class.
If the DbContext class already exists, scaffolding does not register it. 
Also the Startup needs to have a `IConfigurationRoot` property. 

I have made  the needed changes for Startup in https://github.com/Rick-Anderson/MyMvc/pull/1
After this running the above command should succeed.
