### ISSUE TITLE
Remove references to Microsoft.DotNet.InternalAbstractions

### ISSUE THREAD

**Issue by Eilon** [aspnet/Docs#3198]
Microsoft.DotNet.InternalAbstractions was refactored and renamed as part of 1.1 to Microsoft.DotNet.PlatformAbstractions. We should update our code to no longer reference this package:

https://github.com/aspnet/Docs/search?utf8=%E2%9C%93&q=Microsoft.DotNet.InternalAbstractions&type=

It looks to me that in the one hit on this repo, the package probably isn't even used, so it should be safe to remove anyway.

**Comment by Rick-Anderson** [comment]
@Eilon 
When I remove it I get the following:

Starting test execution, please wait...
[xUnit.net 00:00:00.0827736] Exception discovering tests: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
[xUnit.net 00:00:00.2825538] Catastrophic failure: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetAvailableRunnerReporters(IEnumerable`1 sources)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetRunnerReporter(IEnumerable`1 assemblyFileNames)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTests(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, Func`1 testCaseAccessor)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetAvailableRunnerReporters(IEnumerable`1 sources)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetRunnerReporter(IEnumerable`1 assemblyFileNames)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IRunSettings runSettings, IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)
No test is available in C:\csprojNew\4\Docs\aspnetcore\tutorials\dotnet-watch\sample\WebAppTests\bin\Debug\netcoreapp1.1\WebAppTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

**Comment by Rick-Anderson** [comment]
see https://github.com/dotnet/core/issues/366

**Comment by Rick-Anderson** [comment]
@Eilon  Looks like I need to follow Brad's suggestion:

We're retiring dotnet-test-xunit. You should use xunit.runner.visualstudio from 2.2 beta 4 instead (it works for both the CLI and inside Visual Studio).

**Comment by Rick-Anderson** [comment]
@Eilon  never-mind, updating the version it now works.
