### ISSUE TITLE
A Bug in the Install instructions CentOS 

### ISSUE THREAD

**Issue by paule96** [aspnet/Docs#641]
In the install instrutction for CentOS and derivates is this install command missing:
yum install openssl-devel

Without this you get an error if you run the command dnu restore.

Here a sample Output:

```
[paje@RHEL-7 HelloMvc]$ dnu restore
Microsoft .NET Development Utility CoreCLR-x64-1.0.0-beta7-15532

Restoring packages for /home/paje/dev/Home/samples/1.0.0-beta7/HelloMvc/project.json
Warning: FindPackagesById: Microsoft.AspNet.Server.Kestrel
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Server.Kestrel
  The type initializer for 'libcrypto' threw an exception.
Error: FindPackagesById: Microsoft.AspNet.Server.Kestrel
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Diagnostics
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Diagnostics
  The type initializer for 'libcrypto' threw an exception.
Error: FindPackagesById: Microsoft.AspNet.Diagnostics
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Mvc
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Mvc
  The type initializer for 'libcrypto' threw an exception.
Error: FindPackagesById: Microsoft.AspNet.Mvc
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Server.IIS
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Server.IIS
  The type initializer for 'libcrypto' threw an exception.
Error: FindPackagesById: Microsoft.AspNet.Server.IIS
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Server.WebListener
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.AspNet.Server.WebListener
  The type initializer for 'libcrypto' threw an exception.
Error: FindPackagesById: Microsoft.AspNet.Server.WebListener
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.Framework.Logging.Console
  The type initializer for 'libcrypto' threw an exception.
Warning: FindPackagesById: Microsoft.Framework.Logging.Console
  The type initializer for 'libcrypto' threw an exception.
Error: FindPackagesById: Microsoft.Framework.Logging.Console
  The type initializer for 'libcrypto' threw an exception.
----------
System.TypeInitializationException: The type initializer for 'libcrypto' threw an exception. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Interop.libcrypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.libcrypto.EVP_sha1()
   at Internal.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
   at System.Security.Cryptography.SHA1.Implementation..ctor()
   at System.Security.Cryptography.SHA1.Create()
   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource.ComputeHash(String value)
   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource.<TryCache>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource.<GetAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.Restore.NuGet.NuGetv2Feed.<FindPackagesByIdAsyncCore>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass60_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__60.MoveNext()
----------
Restore failed
The type initializer for 'libcrypto' threw an exception.

NuGet Config files used:
    /home/paje/.config/NuGet/NuGet.Config
    /home/paje/dev/Home/samples/1.0.0-beta7/NuGet.Config

Feeds used:
    https://nuget.org/api/v2/
```

That workaround only work with <= beta7. 
I have open a pull request here: [#642](https://github.com/aspnet/Docs/pull/642)

**Comment by danroth27** [comment]
CentOS is unfortunately not supported in beta8 or RC1. We will re-enable CentOS support in the next milestone release.
