### ISSUE TITLE
dotnet aspnet-codegenerator  crash

### ISSUE THREAD

**Issue by nelfer** [aspnet/Docs#8248]
The command:

```
dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages/Movies --referenceScriptLibraries
```
Crashes with the following error message:
```
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:03.99
```
Was using .Net Core 2.1.200 and upgraded to 2.1.401 and still the same issue. Linux machine, Ubuntu 16.04

**Comment by nelfer** [comment]
Opened it via the wrong tool, so there was no linking. Closing it and creating a new one properly
