### ISSUE TITLE
Sqlite package reference missed

### ISSUE THREAD

**Issue by simutaroman** [aspnet/Docs#8304]
Hi.
Please, add &lt;PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.2"/&gt; to the project file.
Otherwise, you'll get error with UseSqlite() in the:
 services.AddDbContext&lt;MvcMovieContext&gt;(options =&gt;
                  options.UseSqlite("Data Source=MvcMovie.db"));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3acf0cee-ea0e-b1ca-d239-a8f2bb465f5b
* Version Independent ID: 20f61d94-ae6a-af54-e089-dc6be40182a0
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/adding-model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-xplat/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-xplat/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@simutaroman thanks. We hope to get this updated in the next couple of months - hopefully sooner.

**Comment by Jreye039** [comment]
Put this in the first ItemGroup

PackageReference Include="Microsoft.AspNetCore.App"
PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"

Put this in the second ItemGroup

DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0"

This worked for me

**Comment by dviljoen** [comment]
Not for me.


C:\Projects\CallForHelp\CallForHelp.csproj : warning NU1604: Project dependency Microsoft.EntityFrameworkCore.Sqlite does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
C:\Projects\CallForHelp\CallForHelp.csproj : warning NU1701: Package 'SQLite.Native 3.12.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may
not be fully compatible with your project.
C:\Projects\CallForHelp\CallForHelp.csproj : warning NU1604: Project dependency Microsoft.EntityFrameworkCore.Sqlite does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
C:\Projects\CallForHelp\CallForHelp.csproj : warning NU1701: Package 'SQLite.Native 3.12.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may
not be fully compatible with your project.
Startup.cs(12,37): error CS0234: The type or namespace name 'Sqlite' does not exist in the namespace 'Microsoft.EntityFrameworkCore' (are you missing an assembly reference?) [C:\Projects\CallForHelp\CallForHelp.csproj]
Startup.cs(13,37): error CS0234: The type or namespace name 'Sqlite' does not exist in the namespace 'Microsoft.EntityFrameworkCore' (are you missing an assembly reference?) [C:\Projects\CallForHelp\CallForHelp.csproj]
    4 Warning(s)
    2 Error(s)

**Comment by Rick-Anderson** [comment]
Do you have the latest released SDK?

**Comment by Rick-Anderson** [comment]
@dviljoen  why are you targeting the .NET Framework rather than .NET Core? Do you have the lastest .NET Core SDK installed?

**Comment by dviljoen** [comment]
Installed it two days ago. It is the latest.

**Comment by dviljoen** [comment]
And I’m not targeting DOT NET Framework. That’s what it’s doing on its own.

**Comment by dviljoen** [comment]
My .csproj file looks exactly like the one above.

**Comment by fonzi956** [comment]
Getting an error during Scaffold the MovieController:  dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries


System.ArgumentException: '' is not a valid version string.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at NuGet.Versioning.VersionRange.Parse(String value)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFilePath(SingleProjectInfo toolLibrary, NuGetFramework framework, String nugetPackagesRoot)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.TryGetToolLockFile(SingleProjectInfo toolLibrary, NuGetFrameworkframework, String nugetPackagesRoot, LockFile& lockFile)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFile(SingleProjectInfo toolLibrary, NuGetFramework framework, IEnumerable`1 possibleNugetPackagesRoot)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(SingleProjectInfo toolLibraryRange, String commandName, IEnumerable`1 args, IProject project)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, IProject project)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by fonzi956** [comment]
Nevermind I got it 

https://github.com/aspnet/Docs/issues/6430

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.3"/>
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>
</Project>

**Comment by Rick-Anderson** [comment]
Fixed in unified version
