### ISSUE TITLE
Unable to connect to the server (WPF Client,  AspnetCore & SignalR Core)

### ISSUE THREAD

**Issue by aravindkoniki** [aspnet/Docs#8319]
I'm using WPF with asp.net core as sever, for client & server communications we have implemented signalR framework.

It is connecting seamlessly when I'm running project through Visual studio / development environment. When I take setup for WPF application it throughs below exception shown in screen shot.

![image](https://user-images.githubusercontent.com/38941211/44783997-2db74200-ab9d-11e8-842c-d764f9bde7be.png)

I have corrected all the package versions, related to asp.net core, signalR core for client and server, all are under same version specified by Microsoft documentation.

[SignalR Versions](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.1)

Versions I'm using

![image](https://user-images.githubusercontent.com/38941211/44784022-40317b80-ab9d-11e8-9c12-01dd0bde9755.png)

![image](https://user-images.githubusercontent.com/38941211/44784039-49224d00-ab9d-11e8-933a-df1ffd1f4f27.png)

 
Complete Stack trace

Unable to connect to the server with any of the available transports.	at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.SignalR.Client.HubConnection.d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.SignalR.Client.HubConnection.d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at ProMove.Client.Infrastructure.SignalR.Connector.d__7.MoveNext()

Can any one help me on this.

**Comment by anurse** [comment]
Is this just a duplicate of https://github.com/aspnet/SignalR/issues/2868 ?

**Comment by aravindkoniki** [comment]
Sorry, Duplicated
